version: "3.8"
# volumes:
#   dbdata:
services:
  # db:
  #   image: postgres:14-alpine
  #   environment:
  #     - POSTGRES_DB=${DB_DATABASE}
  #     - POSTGRES_USER=${DB_USERNAME}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - type: volume
  #       source: dbdata
  #       target: /var/lib/postgresql/data
  #       volume:
  #         nocopy: true
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   ports:
  #     - "127.0.0.1:5432:5432"
  # app:
  #   image: golang:1.17-alpine
  #   depends_on:
  #     - "db"
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DB_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
  #     - PGX_TEST_DATABASE=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
  #   ports:
  #     - 80:80
  #   command: ['go', 'run', '.']